-- ============================================================
-- Oracle Sequences (Auto-increment IDs)
-- Oracle doesn't have AUTO_INCREMENT like MySQL
-- We use SEQUENCES + TRIGGERS to auto-generate IDs
-- ============================================================

-- Drop sequences if exist
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_users';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_cycles';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_goals';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_reviews';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_ratings';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_feedback';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_competencies';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_comp_ratings';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_faqs';           EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE SEQUENCE seq_users        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_cycles       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_goals        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_reviews      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_ratings      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_feedback     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_competencies START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_comp_ratings START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_faqs         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- Triggers: Auto-populate primary keys using sequences
-- ============================================================

CREATE OR REPLACE TRIGGER trg_users_id
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    IF :NEW.user_id IS NULL THEN
        SELECT seq_users.NEXTVAL INTO :NEW.user_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_cycles_id
BEFORE INSERT ON REVIEW_CYCLES
FOR EACH ROW
BEGIN
    IF :NEW.cycle_id IS NULL THEN
        SELECT seq_cycles.NEXTVAL INTO :NEW.cycle_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_goals_id
BEFORE INSERT ON GOALS
FOR EACH ROW
BEGIN
    IF :NEW.goal_id IS NULL THEN
        SELECT seq_goals.NEXTVAL INTO :NEW.goal_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_reviews_id
BEFORE INSERT ON REVIEWS
FOR EACH ROW
BEGIN
    IF :NEW.review_id IS NULL THEN
        SELECT seq_reviews.NEXTVAL INTO :NEW.review_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_ratings_id
BEFORE INSERT ON RATINGS
FOR EACH ROW
BEGIN
    IF :NEW.rating_id IS NULL THEN
        SELECT seq_ratings.NEXTVAL INTO :NEW.rating_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_feedback_id
BEFORE INSERT ON FEEDBACK
FOR EACH ROW
BEGIN
    IF :NEW.feedback_id IS NULL THEN
        SELECT seq_feedback.NEXTVAL INTO :NEW.feedback_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_competencies_id
BEFORE INSERT ON COMPETENCIES
FOR EACH ROW
BEGIN
    IF :NEW.comp_id IS NULL THEN
        SELECT seq_competencies.NEXTVAL INTO :NEW.comp_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_comp_ratings_id
BEFORE INSERT ON COMPETENCY_RATINGS
FOR EACH ROW
BEGIN
    IF :NEW.cr_id IS NULL THEN
        SELECT seq_comp_ratings.NEXTVAL INTO :NEW.cr_id FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_faqs_id
BEFORE INSERT ON REVIEW_POLICY_FAQS
FOR EACH ROW
BEGIN
    IF :NEW.faq_id IS NULL THEN
        SELECT seq_faqs.NEXTVAL INTO :NEW.faq_id FROM DUAL;
    END IF;
END;
/

COMMIT;